# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'XellissimeBook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  # Pods for XellissimeBook

  target 'XellissimeBookTests' do
    inherit! :search_paths
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
  end

end
